// <auto-generated />
using System;
using GeoVial.WebApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoVial.WebApi.Migrations
{
    [DbContext(typeof(GeoVialDbContext))]
    [Migration("20260617124628_RelevamientosYMarcadores")]
    partial class RelevamientosYMarcadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GeoVial.WebApi.Domain.AsignacionAgente", b =>
                {
                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdAgente")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.HasKey("RelevamientoId", "IdAgente");

                    b.HasIndex("IdAgente");

                    b.ToTable("asignaciones_agente", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.MarcadorGeografico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelevamientoId");

                    b.ToTable("marcadores", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Relevamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdJefeArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TramoVial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdJefeArea");

                    b.ToTable("relevamientos", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdAdministrador")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.AsignacionAgente", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdAgente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany("Asignaciones")
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.MarcadorGeografico", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany("Marcadores")
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Relevamiento", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdJefeArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Usuario", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Relevamiento", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Marcadores");
                });
#pragma warning restore 612, 618
        }
    }
}
