// <auto-generated />
using System;
using GeoVial.WebApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoVial.WebApi.Migrations
{
    [DbContext(typeof(GeoVialDbContext))]
    [Migration("20260617160216_ConflictosYCierre")]
    partial class ConflictosYCierre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GeoVial.WebApi.Domain.AsignacionAgente", b =>
                {
                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdAgente")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.HasKey("RelevamientoId", "IdAgente");

                    b.HasIndex("IdAgente");

                    b.ToTable("asignaciones_agente", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FotoId")
                        .IsUnique();

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.ConflictoMarcadorMiembro", b =>
                {
                    b.Property<Guid>("ConflictoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarcadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConflictoId", "MarcadorId");

                    b.HasIndex("MarcadorId");

                    b.ToTable("conflictos_marcador_miembro", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.ConflictoMarcadores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Resolucion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResueltoEn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelevamientoId", "Estado");

                    b.ToTable("conflictos_marcadores", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelevamientoId", "Nombre")
                        .IsUnique();

                    b.ToTable("etiquetas", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.EtiquetaMarcador", b =>
                {
                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarcadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("EtiquetaId", "MarcadorId");

                    b.HasIndex("MarcadorId");

                    b.ToTable("etiquetas_marcador", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ObservacionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PendienteUbicacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenciaAlmacen")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObservacionId");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.MarcaSincronizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SubidaConcluida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RelevamientoId", "ClienteId")
                        .IsUnique();

                    b.ToTable("marcas_sincronizacion", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.MarcadorGeografico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdOrigen")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelevamientoId", "ActualizadoEn");

                    b.HasIndex("RelevamientoId", "IdOrigen");

                    b.ToTable("marcadores", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Observacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdOrigen")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarcadorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("MarcadorId");

                    b.ToTable("observaciones", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Relevamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CerradoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdJefeArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TramoVial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdJefeArea");

                    b.ToTable("relevamientos", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdAdministrador")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.AsignacionAgente", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdAgente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany("Asignaciones")
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Comentario", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Foto", null)
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.ConflictoMarcadorMiembro", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.ConflictoMarcadores", null)
                        .WithMany()
                        .HasForeignKey("ConflictoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoVial.WebApi.Domain.MarcadorGeografico", null)
                        .WithMany()
                        .HasForeignKey("MarcadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.ConflictoMarcadores", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany()
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Etiqueta", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany()
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.EtiquetaMarcador", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoVial.WebApi.Domain.MarcadorGeografico", null)
                        .WithMany()
                        .HasForeignKey("MarcadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Foto", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Observacion", null)
                        .WithMany()
                        .HasForeignKey("ObservacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.MarcaSincronizacion", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany()
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.MarcadorGeografico", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Relevamiento", null)
                        .WithMany("Marcadores")
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Observacion", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoVial.WebApi.Domain.MarcadorGeografico", null)
                        .WithMany()
                        .HasForeignKey("MarcadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Relevamiento", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdJefeArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Usuario", b =>
                {
                    b.HasOne("GeoVial.WebApi.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdAdministrador")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GeoVial.WebApi.Domain.Relevamiento", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Marcadores");
                });
#pragma warning restore 612, 618
        }
    }
}
